language: rust
rust:
- stable
- nightly
matrix:
  include:
  - os: osx
  - os: osx
    rust: nightly
  - env: 
      secure: NEQmng2pL4yPDYBvS16qm9IyXISV0BBsFLALlgNYA1ZSA23IPIEZTHvCPFZEApjEq4IjfHyh0r6Z/Je01LYbuTSddYjhxM8GLEFs8IJJdXtS9Xhhx77CZutKFbsEqdtAPzJdp/eSEymcc2nCnG7cj0Z7aFe814UpW+Rm1RVGPyHY/cTrtHEieH9n6bSoR7mB7YoVc6Y3VbBsB99DKhXfuKJXPJGwogo5ihygVR9qDANgJnvd9j5uP2KENxFC+pY9c6HSF9ez/dY8P0+0nfgL/sJPNco+9GdKfKEVrn8IEsGnecKOC5ws2yf8JUa+v70aqbk+cu6UxOh/Uw/CB3igSKqqLkrp5sEsmi/zOzRe0sYLTcVC82DyHkx4jDY1Ej6YtAC84T2pWpSNg+t9BAP/ly3FkB8z3ggTQuT7/fvy2huett+lx27lLcnEa33DrclIRsHvHq4kCk7cmTga1VawNv1cJtMy97PMH9BNw9gLGbTxeuqvywEcZKsT589yFzYC03ZEJPAV13wOMfA7e3y+GY+oCBdqjTcoHUAarfPf3Lx0FBazRQpyxB48ngaXdewNNQs2KdRkFb2LkxCoExxNX69+X8gxCU56fmiXtNukh7lLZ0LpA/oGGgUs821ReGnJ/I+EhioYFISot81Wecx54xRHsVJ7dOQXBAmpEjp+zWg=
    script:
      - wget -c https://github.com/alexcrichton/cargo-vendor/releases/download/0.1.13/cargo-vendor-0.1.13-x86_64-unknown-linux-musl.tar.gz
      - tar xzvfp cargo-vendor-0.1.13-x86_64-unknown-linux-musl.tar.gz
      - git clone $CARGO_VENDORIZED_REPOSITORY sit-cargo-deps
      - (cd sit-cargo-deps && cp README.md ../cargo-deps-readme && git rm -rf * && mv ../cargo-deps-readme README.md && git add -f README.md)
      - cargo-vendor-0.1.13-x86_64-unknown-linux-musl/cargo-vendor vendor sit-cargo-deps
      - (cd sit-cargo-deps && git add -f * && git -c user.name="SIT Build Bot" -c user.email="bot@sit-it.org" commit -m "Updated cargo deps for $TRAVIS_COMMIT" && git tag deps-`git rev-parse --short $TRAVIS_COMMIT` && git push && git push --tags)
