os: Visual Studio 2015

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc

install:
  - ps: |
          $path = [Environment]::GetEnvironmentVariable("path", "machine")
          $newPath = ($path.Split(';') | Where-Object { $_ -eq 'C:\ProgramData\chocolatey\bin' }) -join ';'
          [Environment]::SetEnvironmentVariable("path", $newPath, "machine")
  - cmd: appveyor-retry choco install gpg4win
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - set PATH=%PATH%;'C:\Program Files (x86)\GnuPG\bin'

build: false

test_script:
  - cargo test

on_failure:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
