[package]
name = "sit"
version = "0.1.0"
description = "SIT's an Issue Tracker"
authors = ["Yurii Rashkovskii <me@yrashk.com>"]
license = "MIT/Apache-2.0"

[dependencies]
clap = "2.29"
chrono = "0.4"
tempfile = "2.2"
sit-core = { path = "../sit-core" }
